version: "3.9"
services: 
    server:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        ports:
            - ${PORT}:${PORT}
        env_file:
            - .env.test
        volumes:
            - ./server:/app/bot/server
            - ./client:/app/bot/client
        restart: always
    database:
        image: "mongo"
        container_name: "mongodb"
        environment:
            - MONGO_INITDB_DATABASE=${DATABASE_NAME}
            - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
        ports:
            - 27017:27017
        volumes:
            - ./mongodb_data_volume:/data/db