FROM node:17
WORKDIR /app/bot/server
COPY server/package*.json ./
RUN yarn install
COPY server/ ./
RUN apt-get -y update\
    && apt-get -y upgrade\
    && apt-get install -y ffmpeg
EXPOSE 4599
CMD [ "yarn", "run", "start:dev"]