FROM node:22
WORKDIR /app/bot/server
COPY server/package.json server/yarn.lock ./
RUN yarn install
COPY shared/ app/bot/shared
COPY server/ ./
RUN apt-get -y update\
    && apt-get -y upgrade\
    && apt-get install -y ffmpeg
EXPOSE 4599
CMD [ "yarn", "run", "start:dev"]