
//region LIMITS
export const APPLICATION_COMMAND_CHOICE_NAME = 100;
export const APPLICATION_COMMAND_CHOICE_VALUE = 100;
export const APPLICATION_COMMAND_MAX_CHOICES = 25;
export const DISCORD_MAX_MESSAGE_LENGTH = 2000;
export const MESSAGE_COMPONENTS_MAX_BUTTONS_PER_ROW = 5;
export const MESSAGE_COMPONENTS_MAX_SELECTS_PER_ROW = 1;
export const MESSAGE_COMPONENTS_MAX_ROWS = 5;
//endregion

export const AUDIO_CONTENT_TYPE = 'audio/mp3';
