export enum ErrorTypes {
    AUTH_FAILED,
    CHANNEL_ID_NOT_FOUND,
    CHANNEL_JOIN_FAILED,
    CHANNEL_NOT_VOICE,
    CONNECTION_NOT_FOUND,
    FILE_NOT_FOUND,
    LOGIN_FAILED,
    PLAY_DISPATCHER_NOT_FOUND,
    PLAY_NOT_ALLOWED,
    SERVER_ID_NOT_FOUND,
    USER_NOT_IN_VOICE_CHANNEL
}